// src/constants/screenNames.js

export const SCREEN_NAMES = {
  INTRO: "INTRO",
  LOGIN: "LOGIN",
  LOGIN_CERTIFICATE: "LOGIN_CERTIFICATE",
  JOIN: "JOIN",
  CERT_FLOW: "CERT_FLOW", // 기존 STEP1/2/3 한 덩어리
  EMAIL_FLOW: "EMAIL_FLOW",
  WELCOME: "WELCOME",
  MAIN: "MAIN",
  PROFILE: "PROFILE",
  SPEND: "SPEND",
  CATEGORY: "CATEGORY",
};
