export const CATEGORY_OPTIONS = [
  { key: "cat_food", label: "식비·외식비", defaultTone: "iris" },
  { key: "cat_loan", label: "대출", defaultTone: "amethyst" },
  { key: "cat_ins", label: "보험", defaultTone: "blush" },
  { key: "cat_house", label: "주거·관리", defaultTone: "lilac" },
  { key: "cat_save", label: "저축", defaultTone: "emerald" },
  { key: "cat_misc", label: "결제·소통", defaultTone: "plum" },
  { key: "cat_other", label: "기타", defaultTone: "lilac" },
];

export const PAYMENT_GROUP_META = {
  card: { key: "card", label: "카드지출" },
  cash: { key: "cash", label: "현금지출" },
};

const OCTOBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-10", label: "급여", amount: 3200000 },
  { id: "income-side-2025-10", label: "기타 수입", amount: 600000 },
];

const OCTOBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_shinhan_2025_10",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 338000,
    paymentKey: "card_shinhan",
    paymentLabel: "신한카드",
    paymentLogo: "S",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "10/07",
  },
  {
    id: "cat_loan_hyundai_2025_10",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 280000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/21",
  },
  {
    id: "cat_ins_kb_2025_10",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 162000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/04",
  },
  {
    id: "cat_house_cash_2025_10",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 273000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/03",
  },
  {
    id: "cat_misc_card_2025_10",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 202000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "10/12",
  },
  {
    id: "cat_other_kb_2025_10",
    categoryKey: "cat_other",
    categoryLabel: "기타",
    amount: 228000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "10/15",
  },
  {
    id: "cat_save_cash_2025_10",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 987000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/28",
  },
];

const DECEMBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-12", label: "급여", amount: 3300000 },
  { id: "income-bonus-2025-12", label: "성과급", amount: 500000 },
];

const DECEMBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_nh_2025_12",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 432000,
    paymentKey: "card_nh",
    paymentLabel: "NH농협카드",
    paymentLogo: "N",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "12/05",
  },
  {
    id: "cat_loan_hyundai_2025_12",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 351000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/20",
  },
  {
    id: "cat_ins_kb_2025_12",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 216000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/09",
  },
  {
    id: "cat_house_cash_2025_12",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 369000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/03",
  },
  {
    id: "cat_misc_card_2025_12",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 270000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "12/14",
  },
  {
    id: "cat_other_kb_2025_12",
    categoryKey: "cat_other",
    categoryLabel: "기타",
    amount: 243000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "12/22",
  },
  {
    id: "cat_save_cash_2025_12",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 1539000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/28",
  },
];

const NOVEMBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-11", label: "급여", amount: 3400000 },
  { id: "income-bonus-2025-11", label: "성과급", amount: 400000 },
];

const NOVEMBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_shinhan_2025_11",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 427000,
    paymentKey: "card_shinhan",
    paymentLabel: "신한카드",
    paymentLogo: "S",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "11/10",
  },
  {
    id: "cat_loan_hyundai_2025_11",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 294000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/22",
  },
  {
    id: "cat_ins_kb_2025_11",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 182000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/06",
  },
  {
    id: "cat_house_cash_2025_11",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 336000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/04",
  },
  {
    id: "cat_misc_card_2025_11",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 224000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "11/12",
  },
  {
    id: "cat_other_kb_2025_11",
    categoryKey: "cat_other",
    categoryLabel: "기타",
    amount: 266000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "11/18",
  },
  {
    id: "cat_save_cash_2025_11",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 931000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/27",
  },
];

const MONTHLY_REPORTS_2025 = [
  {
    key: "2025-12",
    label: "2025년 12월",
    year: "2025",
    budget: {
      incomeBudget: 3800000,
      spendBudget: 3420000,
      variableBudget: 945000,
    },
    incomeEntries: DECEMBER_2025_INCOME_ENTRIES,
    spendEntries: DECEMBER_2025_SPEND_ENTRIES,
  },
  {
    key: "2025-11",
    label: "2025년 11월",
    year: "2025",
    budget: {
      incomeBudget: 3800000,
      spendBudget: 2660000,
      variableBudget: 917000,
    },
    incomeEntries: NOVEMBER_2025_INCOME_ENTRIES,
    spendEntries: NOVEMBER_2025_SPEND_ENTRIES,
  },
  {
    key: "2025-10",
    label: "2025년 10월",
    year: "2025",
    budget: {
      incomeBudget: 3800000,
      spendBudget: 2470000,
      variableBudget: 767000,
    },
    incomeEntries: OCTOBER_2025_INCOME_ENTRIES,
    spendEntries: OCTOBER_2025_SPEND_ENTRIES,
  },
];

const buildYearlyReport = (year, months) => {
  const incomeEntries = months.flatMap((month) =>
    month.incomeEntries.map((entry) => ({
      ...entry,
      id: `${entry.id}-${month.key}`,
      dateLabel: entry.dateLabel || month.label,
    })),
  );
  const spendEntries = months.flatMap((month) =>
    month.spendEntries.map((entry) => ({
      ...entry,
      id: `${entry.id}-${month.key}`,
      dateLabel: entry.dateLabel || month.label,
    })),
  );

  const sumBudget = (key) =>
    months.reduce((accumulator, month) => accumulator + (month.budget?.[key] || 0), 0);

  return {
    key: `${year}-all`,
    label: `${year}년 전체`,
    year,
    isAggregate: true,
    budget: {
      incomeBudget: sumBudget("incomeBudget"),
      spendBudget: sumBudget("spendBudget"),
      variableBudget: sumBudget("variableBudget"),
    },
    incomeEntries,
    spendEntries,
  };
};

const YEARLY_2025_REPORT = buildYearlyReport("2025", MONTHLY_REPORTS_2025);

export const MONTHLY_REPORTS = [YEARLY_2025_REPORT, ...MONTHLY_REPORTS_2025];

export const DEFAULT_INCOME_ENTRIES = YEARLY_2025_REPORT.incomeEntries;
export const DEFAULT_SPEND_ENTRIES = YEARLY_2025_REPORT.spendEntries;
