export const CATEGORY_OPTIONS = [
  { key: "cat_food", label: "식비·외식비", defaultTone: "iris" },
  { key: "cat_loan", label: "대출", defaultTone: "amethyst" },
  { key: "cat_ins", label: "보험", defaultTone: "blush" },
  { key: "cat_house", label: "주거·관리", defaultTone: "lilac" },
  { key: "cat_save", label: "저축", defaultTone: "emerald" },
  { key: "cat_misc", label: "결제·소통", defaultTone: "plum" },
];

export const PAYMENT_GROUP_META = {
  card: { key: "card", label: "카드지출" },
  cash: { key: "cash", label: "현금지출" },
};

const OCTOBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-10", label: "급여", amount: 3700000 },
  { id: "income-side-2025-10", label: "기타 수입", amount: 350000 },
];

const OCTOBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_shinhan_2025_10",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 650000,
    paymentKey: "card_shinhan",
    paymentLabel: "신한카드",
    paymentLogo: "S",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "10/18",
  },
  {
    id: "cat_food_hyundai_2025_10",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 50000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "planned",
    dateLabel: "10/22",
  },
  {
    id: "cat_loan_hyundai_2025_10",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 550000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "10/25",
  },
  {
    id: "cat_ins_kb_2025_10",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 280000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/08",
  },
  {
    id: "cat_house_cash_2025_10",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 500000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "10/03",
  },
  {
    id: "cat_misc_card_2025_10",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 200000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "10/02",
  },
  {
    id: "cat_save_cash_2025_10",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 200000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "10/28",
  },
];

const DECEMBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-12", label: "급여", amount: 4000000 },
  { id: "income-bonus-2025-12", label: "성과급", amount: 180000 },
];

const DECEMBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_nh_2025_12",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 720000,
    paymentKey: "card_nh",
    paymentLabel: "NH농협카드",
    paymentLogo: "N",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "12/06",
  },
  {
    id: "cat_food_kb_2025_12",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 50000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "planned",
    dateLabel: "12/19",
  },
  {
    id: "cat_loan_hyundai_2025_12",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 580000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "12/25",
  },
  {
    id: "cat_ins_kb_2025_12",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 300000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/08",
  },
  {
    id: "cat_house_cash_2025_12",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 500000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "12/03",
  },
  {
    id: "cat_misc_card_2025_12",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 170000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "12/02",
  },
  {
    id: "cat_save_cash_2025_12",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 190000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "12/28",
  },
];

const NOVEMBER_2025_INCOME_ENTRIES = [
  { id: "income-salary-2025-11", label: "급여", amount: 3900000 },
  { id: "income-bonus-2025-11", label: "성과급", amount: 250000 },
];

const NOVEMBER_2025_SPEND_ENTRIES = [
  {
    id: "cat_food_shinhan_2025_11",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 700000,
    paymentKey: "card_shinhan",
    paymentLabel: "신한카드",
    paymentLogo: "S",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "11/11",
  },
  {
    id: "cat_food_hyundai_2025_11",
    categoryKey: "cat_food",
    categoryLabel: "식비·외식비",
    amount: 50000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "planned",
    dateLabel: "11/24",
  },
  {
    id: "cat_loan_hyundai_2025_11",
    categoryKey: "cat_loan",
    categoryLabel: "대출",
    amount: 570000,
    paymentKey: "card_hyundai",
    paymentLabel: "현대카드",
    paymentLogo: "H",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "11/25",
  },
  {
    id: "cat_ins_kb_2025_11",
    categoryKey: "cat_ins",
    categoryLabel: "보험",
    amount: 300000,
    paymentKey: "card_kb",
    paymentLabel: "KB국민카드",
    paymentLogo: "K",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/07",
  },
  {
    id: "cat_house_cash_2025_11",
    categoryKey: "cat_house",
    categoryLabel: "주거·관리",
    amount: 500000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "paid",
    dateLabel: "11/04",
  },
  {
    id: "cat_misc_card_2025_11",
    categoryKey: "cat_misc",
    categoryLabel: "결제·소통",
    amount: 170000,
    paymentKey: "card_other",
    paymentLabel: "우리카드",
    paymentLogo: "W",
    paymentGroupKey: "card",
    paymentGroupLabel: "카드지출",
    spendType: "variable",
    status: "paid",
    dateLabel: "11/02",
  },
  {
    id: "cat_save_cash_2025_11",
    categoryKey: "cat_save",
    categoryLabel: "저축",
    amount: 200000,
    paymentKey: "cash",
    paymentLabel: "현금",
    paymentLogo: "₩",
    paymentGroupKey: "cash",
    paymentGroupLabel: "현금지출",
    spendType: "regular",
    status: "planned",
    dateLabel: "11/27",
  },
];

const MONTHLY_REPORTS_2025 = [
  {
    key: "2025-12",
    label: "2025년 12월",
    year: "2025",
    budget: {
      incomeBudget: 4180000,
      spendBudget: 2510000,
      variableBudget: 1160000,
    },
    incomeEntries: DECEMBER_2025_INCOME_ENTRIES,
    spendEntries: DECEMBER_2025_SPEND_ENTRIES,
  },
  {
    key: "2025-11",
    label: "2025년 11월",
    year: "2025",
    budget: {
      incomeBudget: 4150000,
      spendBudget: 2490000,
      variableBudget: 1150000,
    },
    incomeEntries: NOVEMBER_2025_INCOME_ENTRIES,
    spendEntries: NOVEMBER_2025_SPEND_ENTRIES,
  },
  {
    key: "2025-10",
    label: "2025년 10월",
    year: "2025",
    budget: {
      incomeBudget: 4050000,
      spendBudget: 2430000,
      variableBudget: 1120000,
    },
    incomeEntries: OCTOBER_2025_INCOME_ENTRIES,
    spendEntries: OCTOBER_2025_SPEND_ENTRIES,
  },
];

const buildYearlyReport = (year, months) => {
  const incomeEntries = months.flatMap((month) =>
    month.incomeEntries.map((entry) => ({
      ...entry,
      id: `${entry.id}-${month.key}`,
      dateLabel: entry.dateLabel || month.label,
    })),
  );
  const spendEntries = months.flatMap((month) =>
    month.spendEntries.map((entry) => ({
      ...entry,
      id: `${entry.id}-${month.key}`,
      dateLabel: entry.dateLabel || month.label,
    })),
  );

  const sumBudget = (key) =>
    months.reduce((accumulator, month) => accumulator + (month.budget?.[key] || 0), 0);

  return {
    key: `${year}-all`,
    label: `${year}년 전체`,
    year,
    isAggregate: true,
    budget: {
      incomeBudget: sumBudget("incomeBudget"),
      spendBudget: sumBudget("spendBudget"),
      variableBudget: sumBudget("variableBudget"),
    },
    incomeEntries,
    spendEntries,
  };
};

const YEARLY_2025_REPORT = buildYearlyReport("2025", MONTHLY_REPORTS_2025);

export const MONTHLY_REPORTS = [YEARLY_2025_REPORT, ...MONTHLY_REPORTS_2025];

export const DEFAULT_INCOME_ENTRIES = YEARLY_2025_REPORT.incomeEntries;
export const DEFAULT_SPEND_ENTRIES = YEARLY_2025_REPORT.spendEntries;
