export const CATEGORY_OPTIONS = [
    { key: "cat_food", label: "식비·외식비", defaultTone: "primary" },
    { key: "cat_loan", label: "대출", defaultTone: "dark" },
    { key: "cat_ins", label: "보험", defaultTone: "soft" },
    { key: "cat_house", label: "주거·관리", defaultTone: "green" },
    { key: "cat_misc", label: "결제·소통", defaultTone: "orange" },
];

export const PAYMENT_GROUP_META = {
    card: { key: "card", label: "카드지출" },
    cash: { key: "cash", label: "현금지출" },
};

export const DEFAULT_INCOME_ENTRIES = [
    { id: "income-salary", label: "급여", amount: 3200000 },
    { id: "income-side", label: "기타 수입", amount: 580000 },
];

export const DEFAULT_SPEND_ENTRIES = [
    {
        id: "cat_food_shinhan",
        categoryKey: "cat_food",
        categoryLabel: "식비·외식비",
        amount: 360000,
        paymentKey: "card_shinhan",
        paymentLabel: "신한카드",
        paymentLogo: "S",
        paymentGroupKey: "card",
        paymentGroupLabel: "카드지출",
        spendType: "variable",
        status: "paid",
        dateLabel: "10/18",
    },
    {
        id: "cat_food_hyundai",
        categoryKey: "cat_food",
        categoryLabel: "식비·외식비",
        amount: 300000,
        paymentKey: "card_hyundai",
        paymentLabel: "현대카드",
        paymentLogo: "H",
        paymentGroupKey: "card",
        paymentGroupLabel: "카드지출",
        spendType: "variable",
        status: "planned",
        dateLabel: "10/22",
    },
    {
        id: "cat_loan_hyundai",
        categoryKey: "cat_loan",
        categoryLabel: "대출",
        amount: 550000,
        paymentKey: "card_hyundai",
        paymentLabel: "현대카드",
        paymentLogo: "H",
        paymentGroupKey: "card",
        paymentGroupLabel: "카드지출",
        spendType: "regular",
        status: "planned",
        dateLabel: "10/25",
    },
    {
        id: "cat_ins_kb",
        categoryKey: "cat_ins",
        categoryLabel: "보험",
        amount: 200000,
        paymentKey: "card_kb",
        paymentLabel: "KB국민카드",
        paymentLogo: "K",
        paymentGroupKey: "card",
        paymentGroupLabel: "카드지출",
        spendType: "regular",
        status: "paid",
        dateLabel: "10/08",
    },
    {
        id: "cat_house_cash",
        categoryKey: "cat_house",
        categoryLabel: "주거·관리",
        amount: 140000,
        paymentKey: "cash",
        paymentLabel: "현금",
        paymentLogo: "₩",
        paymentGroupKey: "cash",
        paymentGroupLabel: "현금지출",
        spendType: "regular",
        status: "paid",
        dateLabel: "10/03",
    },
    {
        id: "cat_misc_card",
        categoryKey: "cat_misc",
        categoryLabel: "결제·소통",
        amount: 45000,
        paymentKey: "card_other",
        paymentLabel: "우리카드",
        paymentLogo: "W",
        paymentGroupKey: "card",
        paymentGroupLabel: "카드지출",
        spendType: "variable",
        status: "paid",
        dateLabel: "10/02",
    },
];
